services:
  database:
    image: timescale/timescaledb:latest-pg16
    container_name: database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - database_data:/var/lib/postgresql/data
    restart: always

  api:
    image: postgrest/postgrest:latest
    container_name: api
    environment:
      PGRST_DB_URI: ${PGRST_DB_URI}
      PGRST_DB_SCHEMA: ${PGRST_DB_SCHEMA}
      PGRST_DB_ANON_ROLE: ${PGRST_DB_ANON_ROLE}
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET}
      PGRST_SERVER_PROXY_URI: ${PGRST_SERVER_PROXY_URI}
      PGRST_DB_AGGREGATES_ENABLED: ${PGRST_DB_AGGREGATES_ENABLED}
    ports:
      - '3000:3000'
    depends_on:
      - database
    restart: always

volumes:
  database_data:
    driver: local
